### ISSUE TITLE
"window is not defined" error when using webpack + pusher-js + react

### ISSUE THREAD

**Issue by hderms** [pusher/pusher-js#183]
Issue #48 also describes this problem further down in the comments.
# What

``````
 29% 47/143 build modules15:33:26 web.1  | /Users/rtuser/Sites/rt/rtx/app/node_modules/pusher-js/dist/web/pusher.js:1581
15:33:26 web.1  |           if (window.addEventListener !== undefined) {
15:33:26 web.1  |               ^
15:33:26 web.1  |
15:33:26 web.1  | ReferenceError: window is not defined
15:33:26 web.1  |     at new NetInfo (/Users/rtuser/Sites/rt/rtx/app/node_modules/pusher-js/dist/web/pusher.js:1581:14)
15:33:26 web.1  |     at Object.wsStrategy (/Users/rtuser/Sites/rt/rtx/app/node_modules/pusher-js/dist/web/pusher.js:1601:20)
15:33:26 web.1  |     at __webpack_require__ (/Users/rtuser/Sites/rt/rtx/app/node_modules/pusher-js/dist/web/pusher.js:38:30)
15:33:26 web.1  |     at Object.<anonymous> (/Users/rtuser/Sites/rt/rtx/app/node_modules/pusher-js/dist/web/pusher.js:262:19)
15:33:26 web.1  |     at __webpack_require__ (/Users/rtuser/Sites/rt/rtx/app/node_modules/pusher-js/dist/web/pusher.js:38:30)
15:33:26 web.1  |     at Object.<anonymous> (/Users/rtuser/Sites/rt/rtx/app/node_modules/pusher-js/dist/web/pusher.js:75:18)
15:33:26 web.1  |     at __webpack_require__ (/Users/rtuser/Sites/rt/rtx/app/node_modules/pusher-js/dist/web/pusher.js:38:30)
15:33:26 web.1  |     at Object.<anonymous> (/Users/rtuser/Sites/rt/rtx/app/node_modules/pusher-js/dist/web/pusher.js:66:17)
15:33:26 web.1  |     at __webpack_require__ (/Users/rtuser/Sites/rt/rtx/app/node_modules/pusher-js/dist/web/pusher.js:38:30)
15:33:26 web.1  |     at /Users/rtuser/Sites/rt/rtx/app/node_modules/pusher-js/dist/web/pusher.js:58:18
15:33:26 web.1  | exited with code 1```

``````

**Comment by jackfranklin** [comment]
Can you show how you're importing Pusher into your JS please?

**Comment by hderms** [comment]
I've added `pusher-js` to package.json and `import {Pusher} from 'pusher-js';` in a react file

**Comment by jackfranklin** [comment]
It should be `import Pusher from 'pusher-js'`. Can you try that? I don't think that will get rid of the error though...

What webpack version are you on?

**Comment by hph** [comment]
@hderms Have you resolved your problem? If not, try moving the Pusher part of your application into the `componentDidMount` function of your component, it should be enough.

**Comment by nenad-kolosek** [comment]
this worked for me:
  componentDidMount(){
    var Pusher = require('pusher-js');
    var pusher = new Pusher('45vb7342ca27wqwyb9df609');
  }

**Comment by hph** [comment]
Excellent, in that case I'll consider this issue closed for now, although I think we should try to find a better solution.
