### ISSUE TITLE
"PusherRequestError  Unexpected status code 400"

### ISSUE THREAD

**Issue by owujib** [pusher/pusher-js#727]
This is my first time trying to work with pusher, I copied the code snippet from the docs page and anytime I run the file I get this error 
``` 
Error
at new RequestError (/home/owujib/Documents/node/pusher-js/node_modules/pusher/lib/errors.js:13:16)
at /home/owujib/Documents/node/pusher-js/node_modules/pusher/lib/requests.js:61:17
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async /home/owujib/Documents/node/pusher-js/index.js:28:5 {
name: 'PusherRequestError',
message: 'Unexpected status code 400',
url: 'https://api-eu.pusher.com/apps/1614917/events?auth_key=b87ffd7a43149be003dd&auth_timestamp=1686256597&auth_version=1.0&body_md5=0c3226e92c5e23105c26bb20a16a6774&auth_signature=f93358ffe4474b16f15489bbb07198b2eb34587fb6b9efcfa5184ea08ea10b2a',
error: undefined,
status: 400,
body: 'Expected name parameter to be a string\n'
}
```

**Comment by benjamin-tang-pusher** [comment]
Hi, are you sure you are you using the correct library? Although pusher-js can be run with Node, if you're just triggering an event you should be using the backend server library: https://github.com/pusher/pusher-http-node

**Comment by benjamin-tang-pusher** [comment]
I will close this ticket due to no response.
